---
title: "case_study"
author: "Sharon Kulali"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
library(leaflet)
```


```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
data(nyc_airbnb)

nyc_airbnb =
  nyc_airbnb |> 
  rename(borough = neighbourhood_group) |> 
  mutate(stars = review_scores_location / 2)
```

## Brainstorm questions

- where are airbnbs expensive
  - borough? neighborhood?
  - do other factors (room type) affect price? what about rating?
- how long are airbnbs active?

## where are they expensive

```{r}
nyc_airbnb |> 
 arrange(
    desc(price)
  )

nyc_airbnb |> 
  ggplot(aes(x = price, y = borough)) +
  geom_point()
```

## DO some EDA

```{r}
nyc_airbnb |> 
  count(borough)
```

```{r}
nyc_airbnb |> 
  group_by(borough, room_type) |> 
  summarize(mean_price = mean(price)) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```

```{r}
nyc_airbnb |> 
  group_by(borough, room_type) |> 
  summarize(mean_price = median(price)) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```

```{r}
nyc_airbnb |> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(borough ~ room_type)
```

```{r}
nyc_airbnb |> 
  filter(price >= 9500)
```

```{r}
nyc_airbnb |>
  filter(price < 1000, room_type == "Entire home/apt") |> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(. ~ borough)
```

```{r}
nyc_airbnb |> 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") |> 
  group_by(neighbourhood) |> 
  summarize(
    n_apt = n(),
    mean_price = mean(price)) |> 
  arrange((mean_price))
```

```{r}
nyc_airbnb |> 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = price, y = neighbourhood)) +
  geom_density_ridges()
```

## Try to make a map

```{r}
nyc_airbnb |> 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") |> 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

Try something else entirely

```{r}
nyc_airbnb |> 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") |> 
  sample_n(500) |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~lat, ~long, radius = 0.5)
```

